FROM node:10-buster
RUN apt update && apt install -y imagemagick libtiff5-dev libgsf-1-dev libgsf-1-dev fftw3 orc-0.4 libimagequant-dev
WORKDIR /vips
RUN wget -c https://github.com/libvips/libvips/releases/download/v8.10.5/vips-8.10.5.tar.gz -O - | tar -xz
WORKDIR /vips/vips-8.10.5
RUN ./configure
RUN make >/dev/null
RUN make install >/dev/null
RUN ldconfig >/dev/null
WORKDIR /code
COPY package.json .
RUN yarn
VOLUME [ "/code/node_modules" ]
CMD ["build"]
ENTRYPOINT ["yarn", "run"]
EXPOSE 8080
EXPOSE 3001
