version: "3.7"

services:
  deps:
    build: 
      context: .
      dockerfile: Dockerfile-deps
    image: mrsleeth/v2l:deps
    volumes: 
      - "dependencies:/code/node_modules"

  prototype:
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - "8080:8080"
      - "3001:3001"
    depends_on: 
      - deps
    volumes:
      - ".:/code"
      - "dependencies:/code/node_modules"

volumes:
  dependencies: