version: "3.9"
services:
  v2l:
    image: mrsleeth/v2l:latest
    container_name: v2l-design-system
    ports:
      - "8080:8080"
      - "8081:8081"
      - "3001:3001"
    command: start
    working_dir: /code
    environment: 
      ELEVENTY_ENV: dev
      NODE_ENV: dev
    volumes: 
      - .:/code
      - "11ty-v0.11:/code/node_modules"
volumes:
  11ty-v0.11:
