FROM node:8-stretch
RUN apt update
RUN apt install -y apt-transport-https ca-certificates
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
RUN cat /etc/apt/sources.list.d/yarn.list
RUN apt update
RUN apt install -y yarn
WORKDIR /code
COPY package.json .
COPY yarn.lock .
RUN yarn add ls
RUN cd /code && ls -la