[functions]
  directory = "src/netlify/functions"

[[redirects]]
  from = "/courses/*"
  to = "/login"
  status = 200
  force = true
  conditions = {Role = "Reviewer"}

[[redirects]]
  from = "/courses/*"
  to = "/"
  status = 401
  force = true
