on:
  workflow_dispatch:
  
jobs:
  dotnet:
    runs-on: ubuntu-latest
    
    env:
      ELEVENTY_ENV: dotnet
      
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          lfs: true

