# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ github-actions ]

jobs:
  build:

    runs-on: [self-hosted, macOS]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Publish
      env:
        USER: ${{ secrets.bgyUser }}
        SERVER: ${{ secrets.bgyIP }}  
      run: | 
        ssh "$USER"@"$SERVER"
    # - run: tar -czvf site.tar.gz dist
    # - name: Upload build
    #   uses: actions/upload-artifact@v1
    #   with:
    #     name: build
    #     path:  site.tar.gz
  # deploy_staging:
  #   needs: [build]
  #   runs-on: [self-hosted, macOS]
  #   steps:
  #     - name: Get built site
  #       uses: actions/download-artifact@v1
  #       with:
  #         name: build
  #     - name: Publish
  #       env:
  #         USER: ${{ secrets.bgyUser }}
  #         SERVER: ${{ secrets.bgyIP }}  
  #       run: | 
  #         scp -r build/site.tar.gz $SSH_USER@$SSH_HOST:~/backgroundyellow.net
  #         ssh $SSH_USER@$SSH_HOST tar -xzvf backgroundyellow.net/site.tar.gz -C backgroundyellow.net/v2l/test
